# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37c597bc08bf99b6abf623c90ca4e2a9"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Curaprox Warranty Registration"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
